[package]
version = "0.1.0"
name = "settlement-program"
edition = "2021"

[dependencies]
mina-curves = { workspace = true, features = ["sp1"] }
sp1-zkvm = { workspace = true }
pickles-verifier = { path = "../../crates/pickles-verifier", default-features = false }
zeko_sp1_lib = { path = "../../lib" }
ark-ff = { workspace = true }
mina-poseidon = { workspace = true }
alloy-primitives = { version = "=0.8.20", features = ["sha3-keccak"] }

[target.'cfg(target_os = "zkvm")'.dependencies]
sp1-lib = { workspace = true }

[build-dependencies]
mina-curves = { workspace = true }
pickles-verifier = { path = "../../crates/pickles-verifier" }
poly-commitment = { workspace = true }
sha2 = "0.10"
